### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by alexellis** [derrickpelletier/passport-strava#4]
Hi I'd like to use this middle-ware, but I need some examples.

An example of configuring or new-ing up your strategy would be awesome... I think this is the minimal documentation to make it work as something other people can make use of. Feel free to add more depth..

**Comment by derrickpelletier** [comment]
Makes sense. Unfortunately it'll be a bit until I could add that. If you manage to get it working (consult the examples for github strategy perhaps) i'll definitely accept a pr.

**Comment by derrickpelletier** [comment]
@alexellis I decided to throw some quick notes in the `README.md`. Hopefully that's enough to get you going. There are numerous examples available, so there is no point in being redundant in this module.

Consult the example listed there for the express 4.x facebook quickstart for a really simple way to get started!

**Comment by alexellis** [comment]
@derrickpelletier reading the Github repo's documentation did the trick for me. 

Seriously this repo is about 10x more useful to other people now..  with the little you have added. Cheers
