### ISSUE TITLE
API access token doesn't get attached to the user profile in req

### ISSUE THREAD

**Issue by MathBunny** [derrickpelletier/passport-strava#6]
I'm not sure if I'm missing something but to do subsequent requests, you need the API access token which doesn't get attached after the OAuth handshake. Thus, I had to do something like `profile.accessToken = accessToken;` in `Strategy.prototype.userProfile`. Is there a cleaner solution?

**Comment by derrickpelletier** [comment]
In the example in the readme, the accessToken is returned as a separate param. If you want the accessToken stored with the user, in that example you could just do:

`User.findOrCreate({ stravaId: profile.id, accessToken: accessToken }, (err, ...) { })`

You shouldn't need to modify the `Strategy` prototype at all to use this library. Could you share your implementation?

**Comment by MathBunny** [comment]
Nevermind, you are right. I overlooked it, thanks!
