### ISSUE TITLE
Question: Auth Flow

### ISSUE THREAD

**Issue by emeraldjava** [derrickpelletier/passport-strava#8]
Hi Derrick,

I appreciate that passport-strava handles user authorization for logging in and getting a users details. Is it reasonable to say that the module could be extended to support the strava v3 auth/token flows? I guess I see getting the access_token for a user as an extension to the login flow which passport defines.

I'd use other strava modules for making the more standard API requests there after.

Thanks,
emerald

**Comment by derrickpelletier** [comment]
Hi, i haven't touched this in many many years, so i'm not too sure what the latest api specs are on the strava side.
Definitely open to PRs and improvements though :D
